# Generated by Django 6.0 on 2026-01-21 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('est_payee', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('expeditions', models.ManyToManyField(to='logistics.expedition')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], default='especes', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='billing.facture')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client'], name='billing_fac_client__6551af_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_emission'], name='billing_fac_date_em_835e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['est_payee'], name='billing_fac_est_pay_269ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['facture'], name='billing_pai_facture_fe24c7_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='billing_pai_date_pa_881d62_idx'),
        ),
    ]
