# Generated by Django 6.0 on 2026-01-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='est_payee',
            field=models.CharField(choices=[('impayee', 'Impayée'), ('partielle', 'Partielle'), ('payee', 'Payée')], default='impayee', max_length=20),
        ),
    ]
