# Generated by Django 6.0 on 2026-01-21 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only letters and spaces allowed.')])),
                ('prenom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only letters and spaces allowed.')])),
                ('numero_permis', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Invalid license number format.')])),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('disponibilite', models.BooleanField(default=True)),
                ('date_embauche', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='core_chauff_nom_f19a85_idx'), models.Index(fields=['numero_permis'], name='core_chauff_numero__dd7e0c_idx'), models.Index(fields=['disponibilite'], name='core_chauff_disponi_8576fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only letters and spaces allowed.')])),
                ('prenom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only letters and spaces allowed.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('adresse', models.TextField()),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='core_client_nom_32bb0e_idx'), models.Index(fields=['email'], name='core_client_email_9bd669_idx')],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('zone_geographique', models.CharField(max_length=100)),
                ('tarif_base', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pays', 'ville'],
                'indexes': [models.Index(fields=['ville', 'pays'], name='core_destin_ville_62ca65_idx'), models.Index(fields=['zone_geographique'], name='core_destin_zone_ge_5bb76e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='core_typese_nom_d840a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Invalid license plate format.')])),
                ('type', models.CharField(max_length=50)),
                ('capacite', models.DecimalField(decimal_places=2, help_text='Capacité en kg', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('consommation', models.DecimalField(decimal_places=2, help_text='L/100km', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('en_service', 'En service'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['immatriculation'], name='core_vehicu_immatri_2c2227_idx'), models.Index(fields=['etat'], name='core_vehicu_etat_74958a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_poids', models.DecimalField(decimal_places=2, help_text='Tarif par kg', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tarif_volume', models.DecimalField(decimal_places=2, help_text='Tarif par m3', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destination')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeservice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type_service', 'destination'], name='core_tarifi_type_se_582fc1_idx')],
                'unique_together': {('type_service', 'destination')},
            },
        ),
    ]
