# Generated by Django 6.0 on 2026-01-21 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kilometrage', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('duree', models.DurationField()),
                ('consommation', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('incidents', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^EXP\\d{6}$', 'Format: EXP000001')])),
                ('poids', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('volume', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('en_transit', 'En transit'), ('tri', 'En centre de tri'), ('livraison', 'En cours de livraison'), ('livre', 'Livré'), ('echec', 'Échec de livraison')], default='en_transit', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destination')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeservice')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='logistics.tournee')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lieu', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chauffeur')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='logistics.expedition')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='tournee',
            index=models.Index(fields=['date'], name='logistics_t_date_40c792_idx'),
        ),
        migrations.AddIndex(
            model_name='tournee',
            index=models.Index(fields=['chauffeur'], name='logistics_t_chauffe_d9a70f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournee',
            index=models.Index(fields=['vehicule'], name='logistics_t_vehicul_c1128c_idx'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['numero'], name='logistics_e_numero_6c67e1_idx'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['statut'], name='logistics_e_statut_fd5168_idx'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['date_creation'], name='logistics_e_date_cr_37efd4_idx'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['client'], name='logistics_e_client__47d59a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackinglog',
            index=models.Index(fields=['expedition'], name='logistics_t_expedit_89271c_idx'),
        ),
        migrations.AddIndex(
            model_name='trackinglog',
            index=models.Index(fields=['date'], name='logistics_t_date_e50248_idx'),
        ),
        migrations.AddIndex(
            model_name='trackinglog',
            index=models.Index(fields=['statut'], name='logistics_t_statut_932f38_idx'),
        ),
    ]
