# Generated by Django 6.0 on 2026-01-22 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_expeditionstatushistory_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='agent_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expedition',
            name='suivi_traitement',
            field=models.TextField(blank=True, help_text='Notes de suivi du traitement'),
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('status_change', 'Changement de statut'), ('assignment', 'Assignation'), ('comment', 'Commentaire'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_history', to='logistics.expedition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historique des Actions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['expedition', 'timestamp'], name='logistics_a_expedit_0923be_idx'), models.Index(fields=['user', 'timestamp'], name='logistics_a_user_id_bda8b9_idx')],
            },
        ),
    ]
