# Generated by Django 6.0 on 2026-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_expedition_agent_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='predicted_delivery_time',
            field=models.DateTimeField(blank=True, help_text='Predicted delivery time based on ML model', null=True),
        ),
    ]
