# Generated by Django 6.0 on 2026-01-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_expedition_predicted_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('creee', 'Créée'), ('en_transit', 'En transit'), ('tri', 'En centre de tri'), ('livraison', 'En cours de livraison'), ('livre', 'Livré'), ('echec', 'Échec de livraison')], default='en_transit', max_length=20),
        ),
    ]
