# Generated by Django 6.0 on 2026-01-22 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlog_userfavorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(help_text='Username that was attempted', max_length=150)),
                ('status', models.CharField(choices=[('success', 'Successful'), ('failed', 'Failed')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='users_login_user_id_8deeaf_idx'), models.Index(fields=['status', 'timestamp'], name='users_login_status_c579cf_idx'), models.Index(fields=['ip_address'], name='users_login_ip_addr_84051d_idx')],
            },
        ),
    ]
