# Generated by Django 6.0 on 2026-01-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('retard', 'Retard'), ('perte', 'Perte'), ('endommagement', 'Endommagement'), ('technique', 'Problème technique'), ('autre', 'Autre')], max_length=30)),
                ('severite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='incidents/')),
                ('resolution_details', models.TextField(blank=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.expedition')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.tournee')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['type'], name='support_inc_type_e794a4_idx'), models.Index(fields=['severite'], name='support_inc_severit_ff1177_idx'), models.Index(fields=['priorite'], name='support_inc_priorit_48a2c3_idx'), models.Index(fields=['date'], name='support_inc_date_847627_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('nature', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('resolue', 'Résolue'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('expeditions', models.ManyToManyField(blank=True, to='logistics.expedition')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client'], name='support_rec_client__9e3d04_idx'), models.Index(fields=['statut'], name='support_rec_statut_fefa93_idx'), models.Index(fields=['date'], name='support_rec_date_96c288_idx')],
            },
        ),
    ]
